# PersistentVolumeClaim manifest for storage in the minimal lab
# Requests storage resources from the cluster

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: k8s-minimal
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
