namespace: k8s-minimal

replicaCount: 2

image:
  repository: <YOUR_DOCKERHUB_USERNAME>/k8s-minimal
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

containerPort: 8080

ingress:
  enabled: false
  className: nginx
  host: k8s-minimal.local
